### ISSUE TITLE
vulkan compile error

### ISSUE THREAD

**Issue by PerspectivesLab** [jbikker/lighthouse2#8]
Hi, using visual studio 2017 and compiling the vulkan rendercore i got this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2280	'lh2core::VulkanShader::VulkanShader(const lh2core::VulkanShader &)': attempting to reference a deleted function	rendercore_vulkan_rt	lighthouse2-master\lib\rendercore_vulkan_rt\rendercore.cpp	234	

and breaks at line 234: 
auto rgenShader = VulkanShader( m_Device, "rt_shaders.rgen" );

any info on this ? thx

**Comment by MarijnS95** [comment]
Your Vulkan headers are most likely preventing one or more of the members of `VulkanShader` to be copied, hence why the default copy constructor (`lh2core::VulkanShader::VulkanShader(const lh2core::VulkanShader &)`) has been removed.

Looking at the uses of these classes (those at line 234 and in functions below it) there is no need for this implicit copy through the assignment operator. 
Unfortunately this code is lacking some const-correctness, in particular the arguments to the `VulkanHitGroup` constructor. Otherwise changing the `auto` type to `const auto &` would have been the solution (which can still be done by making the arguments const - that's how the member pointers are classified anyway).

The other solution is to get rid of the copy constructor / reference entirely. Change all the local variables to say `VulkanShader variableName( m_Device, "shader name" );`. For example, the first occurence on line 234 would be changed to `VulkanShader rgenShader( m_Device, "rt_shaders.rgen" );`, likewise for the others.

Edit: This is not just your Vulkan header, it happens here too. The difference seems to be in your particular version of VS2017 being unable to elide the copy operation. However, I would have expected the error for the deleted default copy _asignment operator_, not the copy _constructor_.

**Comment by PerspectivesLab** [comment]
thx for the clarification! it compiles now fine!
